let frame=0,running=null,start=0,elapsed=0;const duration={exit:7000,grip:9000,brake:9000};
const playButtons={exit:document.getElementById('exit-play'),grip:document.getElementById('grip-play'),brake:document.getElementById('brake-play')};
const positions={exit:0,grip:0,brake:0};
function setExit(p){positions.exit=p;document.getElementById('exit-progress').value=Math.round(p*100);document.getElementById('car-slow').setAttribute('transform',`translate(${60+Math.min(p,1)*540},74)`);document.getElementById('car-fast').setAttribute('transform',`translate(${60+Math.min(p*70/60,1)*540},162)`);const exitText=p>=1?'两组均到达终点。平均 112 km/h 的一组先完成相同长度。':p>=60/70?'平均 112 km/h 的一组已经完成直道；96 km/h 的一组仍在行驶。':'比较同样长度的直道：较高的出弯速度，让全段平均速度更高。';const status=document.getElementById('exit-status');if(status.textContent!==exitText)status.textContent=exitText}
// Preserve original ratios for animation; convert only at the display boundary.
function displayKmh(value){return String(Math.round(value*1.6))}
const gripStates=[{speed:12,share:10},{speed:27,share:50},{speed:38.7,share:100}];let gripIndex=0;
function setGrip(i){gripIndex=Math.max(0,Math.min(2,i));const s=gripStates[gripIndex];document.getElementById('grip-speed').textContent=displayKmh(s.speed);document.getElementById('grip-percent').textContent=s.share+'%';document.getElementById('grip-fill').style.width=s.share+'%';document.getElementById('grip-force').setAttribute('x2',String(218-s.share*.78));document.querySelectorAll('[data-grip]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.grip)===gripIndex)));document.getElementById('grip-status').textContent=gripIndex===2?'原图第三档：轮胎的转弯抓地能力已全部用上。继续提速会让轨迹半径增大，见图 1-5。':`原图第 ${gripIndex+1} 档：速度 ${displayKmh(s.speed)} km/h，使用 ${s.share}% 的转弯抓地能力。`}
const brakeStates=[{a:157,b:157,aa:'准备直线制动',bb:'准备直线制动',note:'同样从 251 km/h 开始，目标都是在开始加油的位置降到 85 km/h。'},{a:53,b:57,aa:'已经减速完成，保持车速转弯',bb:'以较高速度入弯，继续减速',note:'差别出现在转向点：只在直线制动的一组已降到 85 km/h；继续制动入弯的一组此处为 91 km/h。'},{a:53,b:53,aa:'抵达开始加油的位置',bb:'抵达开始加油的位置',note:'到加速点时，两组都是 85 km/h。原书比较用时为 6.60 与 6.36 秒，相差 0.24 秒。'}];let brakeIndex=0;
function setBrake(i){brakeIndex=Math.max(0,Math.min(2,i));const s=brakeStates[brakeIndex];document.getElementById('brake-a-speed').textContent=displayKmh(s.a)+' km/h';document.getElementById('brake-b-speed').textContent=displayKmh(s.b)+' km/h';document.getElementById('brake-a-action').textContent=s.aa;document.getElementById('brake-b-action').textContent=s.bb;document.getElementById('brake-status').textContent=s.note;document.querySelectorAll('[data-brake]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.brake)===brakeIndex)))}
function render(kind,p){positions[kind]=p;if(kind==='exit')setExit(p);if(kind==='grip'){const nextGrip=Math.min(2,Math.floor(p*3));if(nextGrip!==gripIndex)setGrip(nextGrip);const t=p*3;const turns=Math.min(t,1)*12/38.7+Math.max(0,Math.min(t-1,1))*27/38.7+Math.max(0,Math.min(t-2,1));const angle=turns*Math.PI*2-Math.PI/2;document.getElementById('grip-car').setAttribute('cx',135+85*Math.cos(angle));document.getElementById('grip-car').setAttribute('cy',125+85*Math.sin(angle))}if(kind==='brake'){const nextBrake=Math.min(2,Math.floor(p*3));if(nextBrake!==brakeIndex)setBrake(nextBrake)}}
function pauseAll(){if(running){playButtons[running].textContent='继续演示';playButtons[running].setAttribute('aria-pressed','false')}running=null;cancelAnimationFrame(frame)}
function tick(now){if(!running)return;const kind=running,p=Math.min(1,(now-start)/duration[kind]);render(kind,p);if(p>=1){playButtons[kind].textContent='重播演示';playButtons[kind].setAttribute('aria-pressed','false');running=null;return}frame=requestAnimationFrame(tick)}
function play(kind){if(running===kind){pauseAll();return}pauseAll();if(reduced.matches){render(kind,1);playButtons[kind].textContent='已显示最终状态';return}if(positions[kind]>=1)positions[kind]=0;running=kind;start=performance.now()-positions[kind]*duration[kind];playButtons[kind].textContent='暂停演示';playButtons[kind].setAttribute('aria-pressed','true');frame=requestAnimationFrame(tick)}
Object.keys(playButtons).forEach(k=>playButtons[k].onclick=()=>play(k));document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{pauseAll();render(b.dataset.reset,0);playButtons[b.dataset.reset].textContent='播放演示'});
document.getElementById('exit-progress').addEventListener('input',e=>{pauseAll();setExit(Number(e.target.value)/100);playButtons.exit.textContent='继续演示'});
document.querySelectorAll('[data-grip]').forEach(b=>b.onclick=()=>{pauseAll();const i=Number(b.dataset.grip);positions.grip=i/3;setGrip(i);playButtons.grip.textContent='播放演示'});document.querySelectorAll('[data-brake]').forEach(b=>b.onclick=()=>{pauseAll();const i=Number(b.dataset.brake);positions.brake=i/3;setBrake(i);playButtons.brake.textContent='播放演示'});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseAll()});reduced.addEventListener('change',()=>pauseAll());
setExit(0);setGrip(0);setBrake(0);
const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting&&entry.target.id===`demo-${running}`)pauseAll()}},{threshold:0});document.querySelectorAll('.demo').forEach(e=>observer.observe(e));
